### ISSUE TITLE
Prepare pointers to be discussed with Labor consultant

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#13]

**Comment by Tanvi-HR** [comment]
Done.

**Comment by anujkhurana** [comment]
Could you please list down the points as comments underneath. Will add/edit to that.

**Comment by Tanvi-HR** [comment]
Confirm no. of people to be classified as employees and consultants respectively. 
TDS v/s Tax on professional fees.- Comparison
Registered address / operational address 
Confirm labor law for consultants. 
Fringe benefits tax
design salary structure template - Give options 
PF & ESIC for contract staff 
list of documents to be signed by employees - Norms to be included for employees and consultants.
No. of staff engaged to be notified to Labor - employees and consultant both? or just employees? 
Permission from local bodies to run business
Govt. norms for IT cos.

**Comment by anujkhurana** [comment]
Looks like a comprehensive list. Can we try and get the lawyer to visit us
at our office? Let's get them in the habit of visiting us rather than us
going to him. I would like to be present in the meeting with him.

If you have another person in mind (other than the one recommended by the
CA) then do contact him as well.

Thanks
