### ISSUE TITLE
Call advertisers - Donapaul & Bambolim (Dubai owner) area.

### ISSUE THREAD

**Issue by Tanvi-HR** [ajency/Day-to-day#17]

**Comment by Tanvi-HR** [comment]
Donapaul area is not open for rent.

**Comment by Tanvi-HR** [comment]
Jude has asked to send a proposal on his email ID which is merz123@gmail.com listing out our company profile, nature of activities, our requirement in terms of area, rent etc. Based on which he will speak to Succour and proceed. @anujkhurana need your help with this.

**Comment by anujkhurana** [comment]
"Ajency.in a team of 20+ and growing to 30 designers and developers. Nature
of work does not require frequent walk ins and customer visits. So there
won't be a commercial board or daily customer visits. Not a call center.
Hours of operation on typical day are 8.00 a.m to 9.00 p.m. We are a 3 year
old company started in march 2012 and have been working out of Nagally
hills Donapaula since Feb 2013. They are free to visit office or speak to
current land lord. www.ajency.in"

This should be enough for now. Do let him know that I spoke to Succor (the
owner) and we have come through <the full name of reference here>.

**Comment by Tanvi-HR** [comment]
Jude will come to Goa and has asked for a meeting at the site on 20th Jan in the first half. Has asked if Assis Araujo can also come? Jude says the bungalow is pretty big, suggests we see the place first and then decide how many rooms we actually need.

**Comment by anujkhurana** [comment]
Say we dont know Assis Araujo and we have asked our reference to Assis to
speak to owner and verify our bonafide credentials. . Talk to Shradha and
pass message to Assis and see if he can have a word with owner.

You should ask Shradha and go see the bunglow from outside.

Tell Jude 20th is fine. Before he takes the effort of coming down can he
share expected rent for entire bunglow and for part of bunglow. This way
his trip won't go waste and we can decide on the spot if we like the place.
